version: '3.7'
services:
  admin:
    image: ghcr.io/unownhash/flygon-admin:main
    container_name: admin
    restart: unless-stopped
    environment:
      ADMIN_GENERAL_USERNAME: admin
      ADMIN_GENERAL_PASSWORD: password

      ADMIN_FLYGON_API_ENDPOINT: http://flygon:9002
      ADMIN_FLYGON_API_SECRET: secret

      ADMIN_GOLBAT_API_ENDPOINT: http://golbat:9001
      ADMIN_GOLBAT_API_SECRET: secret

      ADMIN_KOJI_API_ENDPOINT: http://koji:8080
      ADMIN_KOJI_BEARER_TOKEN: secret
    ports:
      - '9003:9003'
